### ISSUE TITLE
Don't bind everything

### ISSUE THREAD

**Issue by megawac** [kchapelier/node-mathp#4]
It would be **much** more performant to not bind all the functions but keep an internal reference to the ones that require a binding. Otherwise you can do a test to see if binding is necessary (assign to me if you want me to set that up)

Example of perf lose

http://jsperf.com/mathp-binding

**Comment by kchapelier** [comment]
The build system had to be rethought about (for the better) but the branches are now merged. It will be pushed to npm in a few.

I updated the jsperf to compare the old and new implementations ( http://jsperf.com/mathp-binding/3 ).
It's about 99% (!) better for call to generic Math functions. Thanks for raising the issue.
